name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest
          skip-build-cache: true
          skip-pkg-cache: true
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.17
      - name: Install dependencies
        run: |
          sudo apt-get install -y systemtap-sdt-dev libelf1 libelf-dev
          sudo pip3 install stapsdt black isort
      - name: Compile
        run: make -C testdata/
      - name: Test
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go mod tidy
          go test -exec sudo -cover ./...
